## 넘파이

In [25]:
import qrcode
import PIL

def qrcode_maker(text, filename = "qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)



In [26]:
!pip install Pillow


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
qrcode_maker("안녕하세요. 인우입니다. QR테스트 중입니다.")

In [28]:
# numpy

import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]



In [29]:
arr1 = np.array(data1)
arr2 = np.array(data2)

arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [30]:
arr1.shape, arr1.dtype

((5,), dtype('int64'))

In [31]:
arr3 = np.array([[1,2,3],[4,5,6]])

arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [33]:
zz = np.zeros(10)
zz, zz.shape, zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [34]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [35]:
oo = np.ones(7)
oo, oo.shape, oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [36]:
ooo = np.ones((2,10))
ooo, ooo.shape, ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [37]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.Array 연산

In [39]:
# np.Array 연산
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [42]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)


(2, 3) int64
(2, 3) int64


In [ ]:
result0 = arr1
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10


print(result0)
print(result1)
print(result2)
print(result3)


#브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)


[[1 2 3]
 [4 5 6]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[23 35 47]
 [26 38 50]]


In [49]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수

arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim



(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [50]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype = 'str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)


[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [61]:
arr4 = np.full((3,3),13)
arr4


array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [62]:
arr4_1 = np.full((3,3),"조인우")
arr4_1

array([['조인우', '조인우', '조인우'],
       ['조인우', '조인우', '조인우'],
       ['조인우', '조인우', '조인우']], dtype='<U3')

In [64]:
arr5 = np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr6 = np.linspace(0,300,15, endpoint = False, dtype = "int64")
arr6

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240,
       260, 280])

In [67]:
arr7 = np.arange(0,100,20)
arr7

array([ 0, 20, 40, 60, 80])

## 2차원

In [70]:
arr20 = np.array([[1,2],[3,4]])
arr20, arr20.shape, arr20.size, arr20.dtype, arr20.ndim, type(arr20)


(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [ ]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21, arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))

    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22, arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))

    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23, arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))

    
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요: ", e)


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>


In [ ]:
# 수업중