## 넘파이

In [25]:
import qrcode
import PIL

def qrcode_maker(text, filename = "qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)



In [26]:
!pip install Pillow


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
qrcode_maker("안녕하세요. 인우입니다. QR테스트 중입니다.")

In [28]:
# numpy

import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]



In [29]:
arr1 = np.array(data1)
arr2 = np.array(data2)

arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [30]:
arr1.shape, arr1.dtype

((5,), dtype('int64'))

In [31]:
arr3 = np.array([[1,2,3],[4,5,6]])

arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [33]:
zz = np.zeros(10)
zz, zz.shape, zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [34]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [35]:
oo = np.ones(7)
oo, oo.shape, oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [36]:
ooo = np.ones((2,10))
ooo, ooo.shape, ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [37]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.Array 연산

In [39]:
# np.Array 연산
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [42]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)


(2, 3) int64
(2, 3) int64


In [ ]:
result0 = arr1
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10


print(result0)
print(result1)
print(result2)
print(result3)


#브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)


[[1 2 3]
 [4 5 6]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[23 35 47]
 [26 38 50]]


In [49]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수

arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim



(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [50]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype = 'str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)


[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [61]:
arr4 = np.full((3,3),13)
arr4


array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [62]:
arr4_1 = np.full((3,3),"조인우")
arr4_1

array([['조인우', '조인우', '조인우'],
       ['조인우', '조인우', '조인우'],
       ['조인우', '조인우', '조인우']], dtype='<U3')

In [64]:
arr5 = np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr6 = np.linspace(0,300,15, endpoint = False, dtype = "int64")
arr6

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240,
       260, 280])

In [67]:
arr7 = np.arange(0,100,20)
arr7

array([ 0, 20, 40, 60, 80])

## 2차원

In [1]:
arr20 = np.array([[1,2],[3,4]])
arr20, arr20.shape, arr20.size, arr20.dtype, arr20.ndim, type(arr20)


NameError: name 'np' is not defined

In [ ]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21, arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))

    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22, arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))

    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23, arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))

    
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요: ", e)


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>


In [ ]:
# 새로 진행

## 인덱싱 (마스크)

In [34]:
import numpy as np
# 난수 발생

ran_data = np.random.randn(8,4)
ran_data

array([[-1.29731937, -0.56413646,  0.40471554, -1.15203944],
       [ 0.47297263,  0.14836005,  1.01046628,  1.62019711],
       [-1.0115531 , -1.80726294,  0.28445772, -1.84306556],
       [-0.59332108,  0.79175196,  1.2162928 , -0.28645917],
       [ 2.12667   , -1.20146914,  1.46531852,  1.16284572],
       [-1.38709735,  1.18190988,  0.18672511,  0.34785954],
       [-1.07580851, -0.52764759, -0.46745133, -0.34339246],
       [-0.12538477,  1.6707089 , -0.35925318, -0.21763598]])

In [35]:
mask = np.array([True,False,True,False,False,True,True,False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [36]:
ran_data[mask]



array([[-1.29731937, -0.56413646,  0.40471554, -1.15203944],
       [-1.0115531 , -1.80726294,  0.28445772, -1.84306556],
       [-1.38709735,  1.18190988,  0.18672511,  0.34785954],
       [-1.07580851, -0.52764759, -0.46745133, -0.34339246]])

In [37]:
fruit = np.array(['apple','banana','apple','kiwi','orange','apple','apple','melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [38]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [39]:
ran_data[fruit_mask]



array([[-1.29731937, -0.56413646,  0.40471554, -1.15203944],
       [-1.0115531 , -1.80726294,  0.28445772, -1.84306556],
       [-1.38709735,  1.18190988,  0.18672511,  0.34785954],
       [-1.07580851, -0.52764759, -0.46745133, -0.34339246]])

In [40]:
ran_data[(fruit == 'apple')|(fruit == 'orange'), 1:-1] #ran_data[행,열]

array([[-0.56413646,  0.40471554],
       [-1.80726294,  0.28445772],
       [-1.20146914,  1.46531852],
       [ 1.18190988,  0.18672511],
       [-0.52764759, -0.46745133]])

## 인덱스와 마스크의 응용

In [41]:
ran_data[:,0] > 0

array([False,  True, False, False,  True, False, False, False])

In [42]:
ran_data[ran_data[:,:] > 0]

array([0.40471554, 0.47297263, 0.14836005, 1.01046628, 1.62019711,
       0.28445772, 0.79175196, 1.2162928 , 2.12667   , 1.46531852,
       1.16284572, 1.18190988, 0.18672511, 0.34785954, 1.6707089 ])

In [44]:
ran_data[ran_data[2,3] < 0]

array([[[-1.29731937, -0.56413646,  0.40471554, -1.15203944],
        [ 0.47297263,  0.14836005,  1.01046628,  1.62019711],
        [-1.0115531 , -1.80726294,  0.28445772, -1.84306556],
        [-0.59332108,  0.79175196,  1.2162928 , -0.28645917],
        [ 2.12667   , -1.20146914,  1.46531852,  1.16284572],
        [-1.38709735,  1.18190988,  0.18672511,  0.34785954],
        [-1.07580851, -0.52764759, -0.46745133, -0.34339246],
        [-0.12538477,  1.6707089 , -0.35925318, -0.21763598]]])

In [45]:
ran_data > 0

array([[False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [46]:
np.isnan(ran_data)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
fix_data = ran_data[~np.isnan(ran_data).any(axis=1)]
fix_data

array([[-1.29731937, -0.56413646,  0.40471554, -1.15203944],
       [ 0.47297263,  0.14836005,  1.01046628,  1.62019711],
       [-1.0115531 , -1.80726294,  0.28445772, -1.84306556],
       [-0.59332108,  0.79175196,  1.2162928 , -0.28645917],
       [ 2.12667   , -1.20146914,  1.46531852,  1.16284572],
       [-1.38709735,  1.18190988,  0.18672511,  0.34785954],
       [-1.07580851, -0.52764759, -0.46745133, -0.34339246],
       [-0.12538477,  1.6707089 , -0.35925318, -0.21763598]])

In [51]:
fix_data2 = np.abs(fix_data)
fix_data2


array([[1.29731937, 0.56413646, 0.40471554, 1.15203944],
       [0.47297263, 0.14836005, 1.01046628, 1.62019711],
       [1.0115531 , 1.80726294, 0.28445772, 1.84306556],
       [0.59332108, 0.79175196, 1.2162928 , 0.28645917],
       [2.12667   , 1.20146914, 1.46531852, 1.16284572],
       [1.38709735, 1.18190988, 0.18672511, 0.34785954],
       [1.07580851, 0.52764759, 0.46745133, 0.34339246],
       [0.12538477, 1.6707089 , 0.35925318, 0.21763598]])

In [53]:
fix_data3 = np.sqrt(fix_data)
fix_data3

C:\Users\user\AppData\Local\Temp\ipykernel_20820\2500786317.py:1: RuntimeWarning: invalid value encountered in sqrt
  fix_data3 = np.sqrt(fix_data)


array([[       nan,        nan, 0.63617257,        nan],
       [0.68773005, 0.38517535, 1.00521952, 1.27286964],
       [       nan,        nan, 0.53334578,        nan],
       [       nan, 0.88980445, 1.10285665,        nan],
       [1.45831067,        nan, 1.21050342, 1.07835325],
       [       nan, 1.08715679, 0.43211702, 0.58979618],
       [       nan,        nan,        nan,        nan],
       [       nan, 1.29255905,        nan,        nan]])

In [54]:
fix_data4 = np.log(fix_data)

C:\Users\user\AppData\Local\Temp\ipykernel_20820\3733208986.py:1: RuntimeWarning: invalid value encountered in log
  fix_data4 = np.log(fix_data)


In [55]:
fix_data5 = np.sign(fix_data4)
fix_data5

array([[nan, nan, -1., nan],
       [-1., -1.,  1.,  1.],
       [nan, nan, -1., nan],
       [nan, -1.,  1., nan],
       [ 1., nan,  1.,  1.],
       [nan,  1., -1., -1.],
       [nan, nan, nan, nan],
       [nan,  1., nan, nan]])

In [56]:
np.cos(fix_data4)

array([[        nan,         nan,  0.61802304,         nan],
       [ 0.73256229, -0.33095636,  0.9999458 ,  0.88581552],
       [        nan,         nan,  0.30850947,         nan],
       [        nan,  0.97286086,  0.98089087,         nan],
       [ 0.7285748 ,         nan,  0.92789386,  0.98864066],
       [        nan,  0.98606598, -0.10711549,  0.49239544],
       [        nan,         nan,         nan,         nan],
       [        nan,  0.87115429,         nan,         nan]])

In [57]:
# 두 개의 array에 동일한 위치의 요소끼리 비교하기

data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1, data2

(array([[-0.37922538, -1.95104913, -0.70917362,  0.38774734],
        [-0.77675331,  1.03355775,  0.6878191 ,  0.85122026],
        [ 0.01349798, -0.91712629, -1.17444077,  1.56399937],
        [-0.15622601, -0.97245737, -0.64554368, -0.83406779],
        [ 0.10563014, -0.18457343,  0.06201068,  0.36475097],
        [ 0.74942392, -0.33081513,  0.6921769 , -0.76088452],
        [ 1.20665689, -1.7204317 ,  0.67188953, -0.6757221 ],
        [ 0.4856411 ,  0.60345571,  0.74615349, -1.04062941]]),
 array([[-0.66138499,  0.04167097,  0.39432413,  0.71191735],
        [-0.37493968,  0.00753493,  0.51002068,  0.5349258 ],
        [ 1.4447368 , -0.21468165,  0.52125795, -1.32479562],
        [ 1.01340874,  1.32463023, -2.65975722,  1.79295523],
        [-1.30911628, -0.65449304,  1.9761999 , -0.7816918 ],
        [ 0.09337877, -0.30990669,  0.73986889,  1.19504011],
        [-0.96296718,  0.6399715 ,  0.00836007,  0.86188579],
        [-1.84698439,  1.63062609,  0.07653219,  1.02292841]]))

In [58]:
np.maximum(data1, data2)

array([[-0.37922538,  0.04167097,  0.39432413,  0.71191735],
       [-0.37493968,  1.03355775,  0.6878191 ,  0.85122026],
       [ 1.4447368 , -0.21468165,  0.52125795,  1.56399937],
       [ 1.01340874,  1.32463023, -0.64554368,  1.79295523],
       [ 0.10563014, -0.18457343,  1.9761999 ,  0.36475097],
       [ 0.74942392, -0.30990669,  0.73986889,  1.19504011],
       [ 1.20665689,  0.6399715 ,  0.67188953,  0.86188579],
       [ 0.4856411 ,  1.63062609,  0.74615349,  1.02292841]])

In [59]:
np.minimum(data1, data2)

array([[-0.66138499, -1.95104913, -0.70917362,  0.38774734],
       [-0.77675331,  0.00753493,  0.51002068,  0.5349258 ],
       [ 0.01349798, -0.91712629, -1.17444077, -1.32479562],
       [-0.15622601, -0.97245737, -2.65975722, -0.83406779],
       [-1.30911628, -0.65449304,  0.06201068, -0.7816918 ],
       [ 0.09337877, -0.33081513,  0.6921769 , -0.76088452],
       [-0.96296718, -1.7204317 ,  0.00836007, -0.6757221 ],
       [-1.84698439,  0.60345571,  0.07653219, -1.04062941]])

In [60]:
np.maximum(data1, 0) # ReLU(x) 같다.


array([[0.        , 0.        , 0.        , 0.38774734],
       [0.        , 1.03355775, 0.6878191 , 0.85122026],
       [0.01349798, 0.        , 0.        , 1.56399937],
       [0.        , 0.        , 0.        , 0.        ],
       [0.10563014, 0.        , 0.06201068, 0.36475097],
       [0.74942392, 0.        , 0.6921769 , 0.        ],
       [1.20665689, 0.        , 0.67188953, 0.        ],
       [0.4856411 , 0.60345571, 0.74615349, 0.        ]])

In [61]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[0.5       , 0.5       , 0.5       , 0.71191735],
       [0.5       , 0.5       , 0.51002068, 0.5349258 ],
       [1.4447368 , 0.5       , 0.52125795, 0.5       ],
       [1.01340874, 1.32463023, 0.5       , 1.7       ],
       [0.5       , 0.5       , 1.7       , 0.5       ],
       [0.5       , 0.5       , 0.73986889, 1.19504011],
       [0.5       , 0.6399715 , 0.5       , 0.86188579],
       [0.5       , 1.63062609, 0.5       , 1.02292841]])

In [62]:
data = np.random.randn(4,4)
data

array([[-0.1895243 , -1.71833877, -1.73612218,  1.46284846],
       [-0.768619  ,  0.27657523,  0.62543917,  0.71578918],
       [-1.08251421, -0.49868763, -1.32583933,  0.68940933],
       [ 0.64045192,  1.89307414, -0.15716385, -1.46443649]])

In [63]:
np.sum(data)


np.float64(-2.6376583451326496)

In [65]:
np.sum(data, axis = 0)


array([-1.40020559, -0.04737703, -2.59368619,  1.40361047])

In [66]:
np.sum(data, axis = 1)

array([-2.18113679,  0.84918457, -2.21763184,  0.91192572])

In [70]:
np.sum(data[:,1:3], axis = 1)

array([-3.45446095,  0.9020144 , -1.82452696,  1.73591029])

In [71]:
np.mean(data2)

np.float64(0.1700454993225392)

In [73]:
np.mean(data2)

np.float64(0.1700454993225392)

In [74]:
np.mean(data2, axis = 0)

array([-0.32548353,  0.30816904,  0.19585082,  0.50164566])

In [75]:
np.mean(data2, axis = 1)

array([ 0.12163186,  0.16938543,  0.10662937,  0.36780925, -0.19227531,
        0.42959527,  0.13681254,  0.22077557])

In [76]:
np.min(data2, axis = 1)

array([-0.66138499, -0.37493968, -1.32479562, -2.65975722, -1.30911628,
       -0.30990669, -0.96296718, -1.84698439])

In [77]:
# 표준편차
np.std(data2)

np.float64(1.061176234773299)

In [78]:
# 분산
np.var(data2)

np.float64(1.1260950012476356)

In [80]:
np.sort(data2, axis = 0)

array([[-1.84698439, -0.65449304, -2.65975722, -1.32479562],
       [-1.30911628, -0.30990669,  0.00836007, -0.7816918 ],
       [-0.96296718, -0.21468165,  0.07653219,  0.5349258 ],
       [-0.66138499,  0.00753493,  0.39432413,  0.71191735],
       [-0.37493968,  0.04167097,  0.51002068,  0.86188579],
       [ 0.09337877,  0.6399715 ,  0.52125795,  1.02292841],
       [ 1.01340874,  1.32463023,  0.73986889,  1.19504011],
       [ 1.4447368 ,  1.63062609,  1.9761999 ,  1.79295523]])

In [81]:
np.sort(data2)[::-1]

array([[-1.84698439,  0.07653219,  1.02292841,  1.63062609],
       [-0.96296718,  0.00836007,  0.6399715 ,  0.86188579],
       [-0.30990669,  0.09337877,  0.73986889,  1.19504011],
       [-1.30911628, -0.7816918 , -0.65449304,  1.9761999 ],
       [-2.65975722,  1.01340874,  1.32463023,  1.79295523],
       [-1.32479562, -0.21468165,  0.52125795,  1.4447368 ],
       [-0.37493968,  0.00753493,  0.51002068,  0.5349258 ],
       [-0.66138499,  0.04167097,  0.39432413,  0.71191735]])

In [84]:
import numpy as np

student1 = [85,90,88,92]
student2 = [78,81,85,86]
student3 = [92,88,91,90]
student4 = [70,75,72,78]
student5 = [88,85,84,89]

sc_stu = np.array([student1,student2,student3,student4,student5])

# 1. 각 학생의 평균점수
avg_stu = np.mean(sc_stu, axis=1)
print('각 학생의 평균점수:', avg_stu)

# 2. 표준편차가 가장 낮은 학생 찾기
std_stu = np.std(sc_stu, axis=1)
min_std_idx = np.argmin(std_stu)
print(f'표준편차가 가장 낮은 학생: student{min_std_idx+1}, 점수: {sc_stu[min_std_idx]}, 표준편차: {std_stu[min_std_idx]:.2f}')

# 3. 90점 이상이 가장 많은 학생의 점수 나열
count_90 = (sc_stu >= 90).sum(axis=1)
max_90_idx = np.argmax(count_90)
print(f'90점 이상이 가장 많은 학생: student{max_90_idx+1}, 점수: {sc_stu[max_90_idx]}, 90점 이상 개수: {count_90[max_90_idx]}')



각 학생의 평균점수: [88.75 82.5  90.25 73.75 86.5 ]
표준편차가 가장 낮은 학생: student3, 점수: [92 88 91 90], 표준편차: 1.48
90점 이상이 가장 많은 학생: student3, 점수: [92 88 91 90], 90점 이상 개수: 3


In [ ]:
b1r1 = np.arrange(1,10).reshape(3,3)
br2 = np.array([11,22,33])




In [ ]:
# 표준편차
np.std(data2)

np.float64(1.061176234773299)

In [ ]:
# 표준편차
np.std(data2)

np.float64(1.061176234773299)